### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by emptymalei** [InterImm/martian-clock-vuejs#1]
- [ ] Build a clock using vue.js
- [ ] Build a clock that takes input from user
- [ ] Build a converter from earth time to martian time
- [ ] Build a inverse converter

To begin with, I should learn vue.js. Here is the tutorial video.

1. https://laracasts.com/series/learning-vue-step-by-step/episodes/3
